name: Keep Streamlit Apps Alive

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make empty commit
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git commit --allow-empty -m "keep awake"
          git push

