name: Keep Streamlit Apps Alive

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  ping-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Ping care-gb app
        run: curl -s https://care-gb.streamlit.app > /dev/null

      - name: Ping care-sigun app
        run: curl -s https://care-sigun.streamlit.app > /dev/null

